### ISSUE TITLE
请问我照着demo的内容复制的，为啥会报错

### ISSUE THREAD

**Issue by yin11** [giantss/ImagePickerDemo#1]
![image](https://user-images.githubusercontent.com/24215414/47839766-dfb5f900-ddee-11e8-9226-a0ee1376f549.png)
是还缺少什么步骤吗

**Comment by yin11** [comment]
报错
ImagePicker is not defined

**Comment by giantss** [comment]
复制？没太听懂

**Comment by yin11** [comment]
就是，我的页面内容是这样的
![image](https://user-images.githubusercontent.com/24215414/47841065-5523c880-ddf3-11e8-84e9-36be094f5c5d.png)
![image](https://user-images.githubusercontent.com/24215414/47841082-5ead3080-ddf3-11e8-99af-19125e058706.png)
直接把你的index.html里的内容复制来的，想看下效果，可是try catch报错了，是我缺少了什么步骤吗？

**Comment by giantss** [comment]
使用什么命令安装的插件

**Comment by yin11** [comment]
![image](https://user-images.githubusercontent.com/24215414/47841869-f01da200-ddf5-11e8-8de5-89ccbeb0c103.png)
vscode直接这么装的。。。

**Comment by giantss** [comment]
😓，插件的安装地址是 [cordova-plugin-ImagePicker](https://github.com/giantss/cordova-plugin-ImagePicker) 这里只是一个基于该插件可以运行的demo

**Comment by yin11** [comment]
emmm,我再去试试。。。。

**Comment by yin11** [comment]
emmm,大佬我又来了，我照着这个路径装的，然后还是报错
![image](https://user-images.githubusercontent.com/24215414/47891531-8c938300-de8e-11e8-8ee0-4aeb74b4ecd3.png)

**Comment by yin11** [comment]
emmm,安装日志报错有影响吗？
![image](https://user-images.githubusercontent.com/24215414/47891579-c2d10280-de8e-11e8-81e6-6c3c9c54ff10.png)

**Comment by yin11** [comment]
哦，版本太低了，我去找找怎么升级。。。
